---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://fusion809.github.io/hugo"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
...
