# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              The Hornery
github_repo:        fusion809/fusion809.github.io
email:              brentonhorne77@gmail.com
description:        Where fusion809 stores his thoughts and news relating to technology
baseurl:            ""
url:                "https://fusion809.github.io"
twitter_username:   fusion809
github_username:    fusion809
facebook_username:  brenton.horne.7
facebook_name:      Brenton Horne
facebook_username2: sabayon.blog.77
facebook_name2:     The Hornery
highlighter:        rouge
timezone:           Australia/Brisbane
locale:             en_AU
copyright:          "&copy; 2015-2016 Brenton Horne.<br/>
                    Unless otherwise stated all content on this website is licensed under CC-BY-SA-3.0 or compatible licenses.<br/>
                    Linux is a registered trademark of Linus Torvalds; all other trademarks are property of their respective owners."
permalink:          /:year/:month/:day/:title/
exclude:            [vendor]
gems:
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-feed
# Build settings
markdown:           kramdown
author:             Brenton Horne
