# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:                The Hornery
github_repo:          fusion809/fusion809.github.io
email:                brentonhorne77@gmail.com

description:
  "Where Brenton stores his thoughts and news relating to technology."

extended_description:
  "Welcome to *The Hornery*, where I, Brenton Horne, store my thoughts, guides, ramblings and news relating to free and open-source software (FOSS). If you are unfamiliar with the terminology used in the FOSS world, or otherwise find some term here that confuses you, I suggest you see the [glossary](/glossary/) of this website. For copyright information I suggest you see the [copyright page](/copyright/) of this website. Other pieces of general information that you might be interested in can be found in the site's navigation menu.

  This website is powered by the static site generator, [Jekyll](http://jekyllrb.com/), if you would like to create your own Jekyll-powered website and preview it on a Linux platform, I have written a guide on how to do this [here](/how-to-create-your-own-jekyll-site-with-github-pages/)."

baseurl:              "https://fusion809.github.io"
url:                  "https://fusion809.github.io"
twitter_username:     fusion809
github_username:      fusion809
facebook_username:    brenton.horne.7
facebook_name:        Brenton Horne
facebook_username2:   sabayon.blog.77
facebook_name2:       The Hornery
highlighter:          rouge
timezone:             Australia/Brisbane
locale:               en_AU
copyright:            "&copy; 2015-2016 Brenton Horne.<br/>
                      Unless otherwise stated all content on this website is licensed under CC-BY-SA-3.0 or compatible licenses.<br/>
                      Linux is a registered trademark of Linus Torvalds; all other trademarks are property of their respective owners."
permalink:            /:year/:month/:day/:title/
exclude:
- vendor
- assets

gems:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from

asciidoc_ext:         asciidoc,adoc,ad
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style

# Build settings
markdown:             kramdown
author:               Brenton Horne
rec_posts:
  - "/operating-systems/"
  - "/package-development/"
  - "/linux-newcomers/"
  - "/comparison-of-free-operating-systems/"
