# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              The Hornery
email:              brentonhorne77@gmail.com
description:        Where fusion809 stores his thoughts and news relating to technology
baseurl:            ""
url:                "https://fusion809.github.io"
twitter_username:   fusion809
github_username:    fusion809
facebook_username:  brenton.horne.7
facebook_name:      Brenton Horne
facebook_username2: sabayon.blog.77
facebook_name2:     The Hornery
highlighter:        pygments
timezone:           Australia/Brisbane
locale:             en_AU
permalink:          /:year/:month/:day/:title/
exclude:            [
                      "vendor"
                      ,"hugo"
                      ]
gems:
  - jekyll-redirect-from

# Build settings
markdown:           redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
   ,"autolink"
  ]
