source 'https://rubygems.org'
gem 'jekyll', '~> 3.1'
gem 'jekyll-coffeescript'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jekyll-sass-converter'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'kramdown'
gem 'liquid'
gem 'maruku'
gem 'mercenary'
gem 'pygments.rb'
gem 'rdiscount'
gem 'RedCloth'
gem 'terminal-table'
gem 'jekyll-redirect-from'
